plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.2.2'
}

group = 'iot.data.platform'
version = '1.0'

repositories {
    mavenCentral()

    maven {
        url "https://packages.confluent.io/maven"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'org.apache.kafka:connect-api:3.9.1'
}

tasks.named('shadowJar') {
    archiveBaseName.set('rich-gen')
    archiveClassifier.set('')
}